source/order/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.create_order_link, name='orders_create_order_link'),
    url(r'^(?P<uuid>[-\w]{36})$', views.confirm_order, name='orders_confirm_order'),
]

source/quote/models.py
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from django.contrib import messages
from django.core.mail import EmailMessage, get_connection
from django.http import HttpResponseRedirect
from django.shortcuts import render

from wagtail.wagtailadmin.edit_handlers import (FieldPanel, MultiFieldPanel,
                                                PageChooserPanel)
from wagtail.wagtailcore.models import Page
from wagtail.wagtailcore.fields import RichTextField
from wagtail.contrib.wagtailroutablepage.models import RoutablePageMixin, route
from portal.services import limsfm_create_quote
from .forms import QuoteRequestForm


class QuoteRequestFormPage(RoutablePageMixin, Page):
    """
    A Quote Request Form Page that sends an email and calls LIMSfm API to create
    a draft quote.
    """

    intro = RichTextField(blank=True)
    side_panel_title = models.CharField(max_length=255)
    side_panel_content = RichTextField(blank=True)
    success_message = models.CharField(max_length=255)
    thank_you_page = models.ForeignKey(
        'formbuilder.FormThankYouPage',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )
    to_address = models.EmailField(
        max_length=255,
        help_text="Form submissions will be emailed to this address")
    from_address = models.EmailField(
        max_length=255,
        help_text="Form submissions will show as having come from this"
        " address")
    subject = models.CharField(max_length=255, blank=True)

    subpage_types = ['formbuilder.FormThankYouPage']

    content_panels = Page.content_panels + [
        FieldPanel('intro', classname='full'),
        MultiFieldPanel([
            FieldPanel('side_panel_title'),
            FieldPanel('side_panel_content', classname='full'),
        ], "Side Panel"),
        MultiFieldPanel([
            FieldPanel('to_address'),
            FieldPanel('from_address'),
            FieldPanel('subject', classname="full"),
        ], "Email"),
        PageChooserPanel('thank_you_page'),
    ]


    def process_form_submission(self, form):
        try:
            quote_ref = limsfm_create_quote(form.cleaned_data)
        except Exception:
            quote_ref = ''

        # send email
        if self.to_address:
            addresses = [x.strip() for x in self.to_address.split(',')]
            content = []
            content.append('Quote Ref: {}'.format(quote_ref))

            for field in form:
                value = field.value()
                if isinstance(value, list):
                    value = ', '.join(value)
                # Only add the Conference (other) value if the referral type was also Conference (other)
                if field.id_for_label == 'id_conference_other':
                    if form.data['referral_type'] == 'Conference (other)':
                        content.append('{}: {}'.format(field.label, value))
                else:
                    content.append('{}: {}'.format(field.label, value))
            content = '\n'.join(content)

            reply_to = ([form.data['email']] if 'email' in form.data else None)
            subject = '%s [%s %s]' % (self.subject, quote_ref, form.data['name_last'])
            connection = get_connection()
            email = EmailMessage(subject, content, self.from_address, [self.to_address],
                                 connection=connection, reply_to=reply_to)
            email.send(fail_silently=False)


    # def serve(self, request):
    #     if request.method == 'POST':
    #         # honeypot
    #         if len(request.POST.get('url_h', '')):
    #             messages.success(request, self.success_message)
    #             return HttpResponseRedirect(self.url)

    #         form = QuoteRequestForm(request.POST)

    #         if form.is_valid():
    #             self.process_form_submission(form)
    #             if self.thank_you_page:
    #                 return HttpResponseRedirect(self.thank_you_page.url)
    #             else:
    #                 messages.success(request, self.success_message)
    #                 return HttpResponseRedirect(self.url)
    #     else:
    #         form = QuoteRequestForm()

    #     return render(request, 'quote/quote_request_form.html', {
    #         'page': self,
    #         'form': form,
    #     })


    @route(r'^$')
    @route(r'^(?P<service_string>[\w\-]+)/$')
    def service_serve(self, request, service_string = None):
        if request.method == 'POST':
            # honeypot
            if len(request.POST.get('url_h', '')):
                messages.success(request, self.success_message)
                return HttpResponseRedirect(self.url)

            form = QuoteRequestForm(request.POST)

            if form.is_valid():
                self.process_form_submission(form)
                if self.thank_you_page:
                    return HttpResponseRedirect(self.thank_you_page.url)
                else:
                    messages.success(request, self.success_message)
                    return HttpResponseRedirect(self.url)
        else:

            form = QuoteRequestForm()

        return render(request, 'quote/quote_request_form.html', {
            'page': self,
            'form': form,
            'service_string': service_string
        })

source/quote/forms.py
from django import forms

from django.core.exceptions import ValidationError
from django.utils.safestring import mark_safe
from django.utils.translation import ugettext as _
from phonenumber_field.formfields import PhoneNumberField

from country.models import Country

FUNDING_TYPE_CHOICES = [
    ('', '---'),
    ('BBSRC funded', 'BBSRC funded'),
    ('Non-commercial', 'Other non-commercial (Academic/Charity)'),
    ('Industry', 'Industry'),
    ('University of Birmingham', 'University of Birmingham'),
]

REFERRAL_TYPE_CHOICES = [
    ('', '---'),
    ('University of Birmingham', 'University of Birmingham'),
    ('Microbiology Society Conference', 'Microbiology Society Conference'),
    ('Conference (other)', 'Conference (other)'),
    ('Word of Mouth / Recommendation', 'Word of Mouth / Recommendation'),
    ('Search Engine', 'Search Engine'),
    ('Social Media', 'Social Media'),
    ('Publication / Academic Acknowledgement', 'Publication / Academic Acknowledgement'),
]

SAMPLE_TYPE_CHOICES = [
    ('Viral', 'Viral (including phages)'),
    ('Bacteria', 'Bacteria'),
    ('Fungi', 'Fungi'),
    ('> Biosafety 2', '> Biosafety 2'),
    ('GMM', 'GMM'),
    ('> 10 MB', '> 10 MB (please note that we only sequence organisms < 50 MB)'),
    ('Other', 'Other - please specify in comments box at end of form'),
]

BATCH_TYPE_CHOICES = [
    ('all together', 'Sending all samples together'),
    ('batches', 'Sending in multiple batches')
]

NAME_TITLE_CHOICES = [
    ('', ''),
    ('Dr', 'Dr'),
    ('Prof', 'Prof'),
    ('Mr', 'Mr'),
    ('Miss', 'Miss'),
    ('Ms', 'Ms'),
    ('Mrs', 'Mrs'),
    ('Mx', 'Mx'),
    ('Sir', 'Sir'),
    ('Lord', 'Lord')
]


class QuoteRequestForm(forms.Form):
    name_title = forms.ChoiceField(
        choices=NAME_TITLE_CHOICES,
        label=_("Title"),
        required=False)
    name_first = forms.CharField(max_length=50, label=_("First name"))
    name_last = forms.CharField(max_length=50, label=_("Last name"))
    email = forms.EmailField(label=_("Email address"))
    phone = PhoneNumberField(
        label=_("Phone number"),
        help_text=_("International customers: please enter a country code "
                    "e.g. +1-541-754-3010 for a US number."))
    primary_contact_is_pi = forms.BooleanField(
        label="Same as primary contact",
        required=False)
    pi_name_title = forms.ChoiceField(
        choices=NAME_TITLE_CHOICES,
        label=_("Title"),
        required=False)
    pi_name_first = forms.CharField(
        label=_("First name"),
        max_length=50,
        required=False)
    pi_name_last = forms.CharField(
        label=_("Last name"),
        max_length=50,
        required=False)
    pi_email = forms.EmailField(label=_("Email address"), required=False)
    organisation = forms.CharField(
        max_length=50,
        label=_("Institution / Company"))
    department = forms.CharField(max_length=50, required=False)
    street_line_1 = forms.CharField(
        max_length=50,
        label=_("Address lines"),
        widget=forms.TextInput(
            attrs={'placeholder': "e.g. Room W126, Biosciences building."}))
    street_line_2 = forms.CharField(
        max_length=50,
        label=_("Address line 2"),
        required=False)
    street_line_3 = forms.CharField(
        max_length=50,
        label=_("Address line 3"),
        required=False)
    city = forms.CharField(max_length=50)
    region = forms.CharField(
        max_length=50,
        label=_("Region / State"),
        required=False)
    postcode = forms.CharField(
        max_length=10,
        label=_("Postcode / Zip"),
        required=False)
    country = forms.ModelChoiceField(
        queryset=Country.objects.all(),
        to_field_name='name',
        widget=forms.TextInput(),
        error_messages={
            'required': "Sample collection country is required.",
            'invalid_choice': "Please select a valid country from the list."
        })
    funding_type = forms.ChoiceField(choices=FUNDING_TYPE_CHOICES)
    bbsrc_code = forms.CharField(required=False, label=_("BBSRC grant code"))
    is_grant_application = forms.BooleanField(required=False, label=_("This quote is for a grant application"))
    is_confidential = forms.BooleanField(required=False, label=_("Is confidential"))
    sample_types = forms.MultipleChoiceField(
        label=_("Which of the following apply to your samples?"),
        help_text=_("Select all that apply"),
        widget=forms.SelectMultiple(attrs={"size": len(SAMPLE_TYPE_CHOICES)}),
        choices=SAMPLE_TYPE_CHOICES,
    )
    num_dna_samples = forms.IntegerField(
        min_value=0,
        initial=0,
        required=False,
        label=_("No. of DNA samples"))
    num_strain_samples = forms.IntegerField(
        min_value=0,
        initial=0,
        required=False,
        label=_("No. of strain samples"))
    num_enhanced_strain_samples = forms.IntegerField(
        min_value=0,
        initial=0,
        required=False,
        label=_("No. strains for enhanced sequencing"))
    confirm_strain_bsl2 = forms.BooleanField(
        required=False,
        label=_("Confirm that your strains comply with the strain submission criteria"))
    confirm_enhanced_strain_bsl2 = forms.BooleanField(
        required=False,
        label=_("Confirm that your enhanced strains comply with the strain submission criteria"))
    batch_type = forms.ChoiceField(
        choices=BATCH_TYPE_CHOICES,
        initial='all together')
    referral_type = forms.ChoiceField(
        choices=REFERRAL_TYPE_CHOICES,
        label=_("Where did you hear about us?"))
    conference_other = forms.CharField(required=False, label=_("Conference (other)"))
    comments = forms.CharField(required=False, widget=forms.Textarea())

    def clean(self):
        cleaned_data = super(QuoteRequestForm, self).clean()
        non_field_errors = []

        funding_type = cleaned_data.get('funding_type')
        bbsrc_code = cleaned_data.get('bbsrc_code')
        is_grant_application = cleaned_data.get('is_grant_application')
        sample_types = cleaned_data.get('sample_types')
        num_dna_samples = cleaned_data.get('num_dna_samples')
        num_strain_samples = cleaned_data.get('num_strain_samples')
        num_enhanced_strain_samples = cleaned_data.get("num_enhanced_strain_samples")
        confirm_strain_bsl2 = cleaned_data.get('confirm_strain_bsl2')
        confirm_enhanced_strain_bsl2 = cleaned_data.get('confirm_enhanced_strain_bsl2')
        primary_contact_is_pi = cleaned_data.get('primary_contact_is_pi')
        pi_name_title = cleaned_data.get('pi_name_title')
        pi_name_first = cleaned_data.get('pi_name_first')
        pi_name_last = cleaned_data.get('pi_name_last')
        pi_email = cleaned_data.get('pi_email')
        referral_type = cleaned_data.get('referral_type')
        conference_other = cleaned_data.get('conference_other')
        comments = cleaned_data.get('comments')

        if num_strain_samples is None:
            num_strain_samples = 0
        if num_dna_samples is None:
            num_dna_samples = 0
        if num_enhanced_strain_samples is None:
            num_enhanced_strain_samples = 0

        if primary_contact_is_pi:
            cleaned_data['pi_name_title'] = ''
            cleaned_data['pi_name_first'] = ''
            cleaned_data['pi_name_last'] = ''
            cleaned_data['pi_email'] = ''
        else:
            if not pi_name_first:
                self.add_error(
                    'pi_name_first',
                    ValidationError(_("Principal investigator first name is required."),
                    code='required'))
            if not pi_name_last:
                self.add_error(
                    'pi_name_last',
                    ValidationError(_("Principal investigator last name is required."),
                    code='required'))
            if not pi_email:
                self.add_error(
                    'pi_email',
                    ValidationError(_("Principal investigator email is required."),
                    code='required'))

        if (funding_type == 'BBSRC funded' and not bbsrc_code):
            bbsrc_error = ValidationError(_("BBSRC code is required."))
            self.add_error('bbsrc_code', bbsrc_error)
            non_field_errors.append(bbsrc_error)

        if (num_strain_samples > 0 and not confirm_strain_bsl2):
            bsl2_error = ValidationError(
                _("You must confirm that your strains comply with the strain submission criteria."))
            self.add_error('confirm_strain_bsl2', bsl2_error)
            non_field_errors.append(bsl2_error)

        if (num_enhanced_strain_samples > 0 and not confirm_enhanced_strain_bsl2):
            enhanced_bsl2_error = ValidationError(
                _("You must confirm that your enhanced strains comply with the strain submission criteria."))
            self.add_error('confirm_enhanced_strain_bsl2', enhanced_bsl2_error)
            non_field_errors.append(enhanced_bsl2_error)

        if not (num_strain_samples or num_dna_samples or num_enhanced_strain_samples):
            non_field_errors.append(
                ValidationError(
                    _("A total sample quantity of at least one (strain or DNA)"
                      " is required."))
            )

        # Validate Referral Type and Conference (other) fields

        if referral_type == 'Conference (other)' and not conference_other:
            conference_other_error = ValidationError(
                _('Please enter the name of the conference at which you heard about us.'))
            self.add_error('conference_other', conference_other_error)
            non_field_errors.append(conference_other_error)

        if non_field_errors:
            raise ValidationError(non_field_errors)

        # If there were no validation errors

        ## PREPEND EXTRA FIELDS TO COMMENTS (for displaying in the LIMS):

source/quote/templates/quote/base.html
{% extends "base.html" %}

source/quote/templates/quote/quote_request_form.html
{% extends "quote/base.html" %}
{% load bootstrap3 wagtailcore_tags static pipeline %}

{% block title %}Quote Request Form{% endblock %}

{% block extra_js %}
  {% javascript 'mngweb_quote' %}


  <script>
    $(document).ready(function() {
      // $("#notificationModal").modal("show");
      var initialFundingType = "{{service_string|safe}}";
      console.log(initialFundingType);
      switch (initialFundingType) {
        case "BBSRC":
          $("#id_funding_type option[value='BBSRC funded']").prop("selected", true);
          break;
        case "Non-c":
          $("#id_funding_type option[value='Non-commercial']").prop("selected", true);
          break;
        case "Indus":
          $("#id_funding_type option[value='Industry']").prop("selected", true);
          break;
        default:
          break;
      }
    });
  </script>
{% endblock %}
{% block extra_css %}
<style>
  .dateText {
    font-weight: bolder;
    font-size: 16px;
    color: coral;
  }

  #dangerWell {
    background-color: #ff8787;
    font-size: 16px;
  }

  .panel-danger ul {
    padding-left: 1.2em;
  }

  .panel-body > .table {
    margin-bottom: 0;
  }

  .panel-body .table ul {
    padding-left: 1rem;
    margin-bottom: 0;
  }

  .comments-link, .criteria-link {
    cursor: pointer;
  }

</style>
{% endblock %}
{% block body_class %}template-quoterequestformpage{% endblock %}

{% block full_jumbo %}
  <div class="jumbotron bg-grey">
    <div class="container">
      <h1>{{ page.title }}</h1>
    </div>
  </div>
{% endblock %}

{% block content %}

<div id="notificationModal" class="modal fade" role="dialog" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h2 class="modal-title">Important Notice</h2>
            </div>
            <div class="modal-body">
                <div class="container-fluid">
                    <div class="container-fluid">
                        <div class="col-md-12">

                            Due to University of Birmingham closure around the christmas period,
                            any samples received after the <span class="dateText">15th December</span> will not be processed
                            untill after christmas.


                            <h4>The last sequencing run for this year is due for early December.</h4>

                            <div class="col-md-12"><hr></div>
                            <div class="col-md-12" align="right">
                                <p>Thank you, MicrobesNG Team</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



  <div class="container">

    <div class="row">

      <div class="col-md-8">
        <div class="messages">
          {% include 'includes/messages.html' %}
          {% bootstrap_form_errors form %}
        </div>

        <div class="panel panel-danger">
          <div class="panel-heading"><h4>Important notice!</h4></div>
          <div class="panel-body">
            <p><strong>Please under no circumstances post samples to us before you receive your barcodes or strain tubes.</strong></p>
          </div>
        </div>

        {{ self.intro|richtext }}

        <form action="{% pageurl page %}" method="POST">
          {% csrf_token %}
          {% include 'includes/honeypot_form_field.html' %}

          <h3 class="section-header">Primary contact details</h3>

          <p>Please enter the details of the individual primarily responsible for the day-to-day management of this sequencing project.</p>

          <div class="row">
            <div class="col-md-2">
              {% bootstrap_field form.name_title %}
            </div>
            <div class="col-md-5">
              {% bootstrap_field form.name_first %}
            </div>
            <div class="col-md-5">
              {% bootstrap_field form.name_last %}
            </div>
          </div>

          <div class="row">
            <div class="col-md-7">
              {% bootstrap_field form.email %}
            </div>
            <div class="col-md-5">
              {% bootstrap_field form.phone %}
            </div>
          </div>

          <h3 class="section-header">Principal investigator (grant holder)</h3>
          <p>Please enter the details of the principal investigator (grant holder) for this project.</p>

          <div class="row">
            <div class="col-md-7">
              {% bootstrap_field form.primary_contact_is_pi %}
            </div>
          </div>

          <div class="row pi-contact-fields">
            <div class="col-md-2">
              {% bootstrap_field form.pi_name_title %}
            </div>
            <div class="col-md-5">
              {% bootstrap_field form.pi_name_first %}
            </div>
            <div class="col-md-5">
              {% bootstrap_field form.pi_name_last %}
            </div>
          </div>

          <div class="row pi-contact-fields">
            <div class="col-md-7">
              {% bootstrap_field form.pi_email %}
            </div>
          </div>


          <h3 class="section-header">Postal address</h3>
          <p>This is the address that we will post barcodes, bead tubes and return labels to, and is <strong>not used for billing</strong>.</p>
          <p>Please make sure to include the building or relevant department.</p>

          {% bootstrap_field form.organisation field_class="organisation-typeahead" %}
          {% bootstrap_field form.department %}
          {% bootstrap_field form.street_line_1 label="Address lines" %}
          {% bootstrap_field form.street_line_2 show_label=False %}
          {% bootstrap_field form.street_line_3 show_label=False %}
          <div class="row">
            <div class="col-md-6">
              {% bootstrap_field form.city %}
            </div>
            <div class="col-md-6">
              {% bootstrap_field form.region %}
            </div>
          </div>
          <div class="row">
            <div class="col-md-3">
              {% bootstrap_field form.postcode %}
            </div>
            <div class="col-md-9">
              {% bootstrap_field form.country field_class="country-typeahead" %}
            </div>
          </div>
          <p><strong>Will payment be made by a different company or institution?</strong></p>
          <p>If yes, please enter the address of the paying company or institution to the <a class="comments-link">comments box below</a>.</p>

          <h3 class="section-header">Sample information</h3>
          <p>Please note: the confidential service costs £100 regardless of funding type.
              Otherwise, your data will be embargoed for 1 year, which can be extended by written
              request (see terms).</p>
          <div class="row">
            <div class="col-md-6">
              {% bootstrap_field form.funding_type %}
              {% bootstrap_field form.is_grant_application %}
              {% bootstrap_field form.is_confidential %}
            </div>
            <div class="col-md-6">
              {% bootstrap_field form.bbsrc_code %}
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              {% bootstrap_field form.sample_types %}
            </div>
          </div>
          <div id="viral_fungal_note" class="panel panel-warning" hidden>
            <div class="panel-body">
              Please note, we only accept fungi and viruses as DNA as per our <a class="criteria-link">strain submission criteria</a>.
            </div>
          </div>
          <div class="row">
            <div class="col-md-4">
              {% bootstrap_field form.num_dna_samples %}
              <div class="panel panel-success"><div class="panel-body"><i class="fa fa-globe text-success"></i> DNA samples can be sent from customers worldwide</div></div>
            </div>
            <div class="col-md-4">
              {% bootstrap_field form.num_strain_samples %}
              <div class="panel panel-success"><div class="panel-body"><i class="fa fa-globe text-success"></i> Strains can be sent from customers worldwide</div></div>
              {% bootstrap_field form.confirm_strain_bsl2 %}
            </div>
            <div class="col-md-4">
              {% bootstrap_field form.num_enhanced_strain_samples %}
              <div class="panel panel-success"><div class="panel-body"><i class="fa fa-globe text-success"></i> Enhanced strains can be sent from customers worldwide</div></div>
              {% bootstrap_field form.confirm_enhanced_strain_bsl2 %}
            </div>
          </div>

          <div class="col-md-12">
            <div class="panel panel-default">
              <div class="panel-body">
                <table class="table">
                  <tbody>
                    <tr>
                      <th>Total number of samples:</th>
                      <td id="quote-total-qty"></td>
                    </tr>
                    <tr>
                      <th>Price per sample:</th>
                      <td id="quote-unit-price"></td>
                    </tr>
                    <tr>
                      <th>
                        Estimated Total (ex. VAT&nbsp;
                        <span data-toggle="tooltip" title="VAT is applicable for all institutions/businesses paying from within the UK as we provide a service and not a product. (VAT exemption certificates are not applicable for the purchase of services)"><i class="fa fa-question-circle"></i></span>
                        ):
                      </th>
                      <td id="quote-grand-total-price"></td>
                    </tr>
                    <tr>
                      <th>What's included?</th>
                      <td>
                        <ul>
                          <li>DNA extraction (strains only)</li>
                          <li>Library preparation</li>
                          <li>Sequencing</li>
                          <li>Basic bioinformatics (annotation, assembly, variant calling)</li>
                        </ul>
                      </td>
                    </tr>
                    <tr>
                      <th>Sample preparation protocols:</th>
                      <td>
                        <ul>
                          <li><a href="/documents/3/MicrobesNG_preparing_your_bead_tubes.pdf" target="_blank">Bead tube submission</a></li>
                          <li><a href="/documents/2/DNA_Submission_Protocol.pdf" target="_blank">DNA submission</a></li>
                        </ul>
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>

          <h3 class="section-header">Further details</h3>
          {% bootstrap_field form.batch_type %}
          {% bootstrap_field form.referral_type %}
          {% bootstrap_field form.conference_other %}
          {% bootstrap_field form.comments %}

          {% buttons %}
            <button type="submit" class="btn btn-success button-lg">
              <i class="fa fa-envelope"></i> Request quote
            </button>
          {% endbuttons %}
        </form>
        <!-- <div class="col-md-12">
          <div class="col-md-12 well" id="dangerWell">
              <ul>
                  <li>Cutoff date for receipt of samples: <b>15th December</b></li>
                  <li>Last sequencing run for the year scheduled for early December.</li>
              </ul>
          </div>
        </div> -->
      </div>

      {# Sidebar #}
      <aside class="col-md-4 aside">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h4>{{ page.side_panel_title }}</h4>
          </div>
          <div class="panel-body">
            {{ page.side_panel_content|richtext }}
          </div>
        </div>
      </aside>

    </div>
  </div>
{% endblock %}